CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  site_name TEXT,
  logo_url TEXT,
  banner_text TEXT,
  phone TEXT,
  address TEXT,
  work_hours TEXT,
  telegram_url TEXT,
  instagram_url TEXT,
  facebook_url TEXT,
  humo_card TEXT,
  uzcard_card TEXT,
  visa_card TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Policy to allow anonymous read access (if needed for public website)
ALTER TABLE settings ENABLE ROW LEVEL SECURITY;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Public Read Settings'
    ) THEN
        CREATE POLICY "Public Read Settings" ON settings FOR SELECT USING (true);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_policies WHERE policyname = 'Admin Update Settings'
    ) THEN
        CREATE POLICY "Admin Update Settings" ON settings FOR ALL USING (auth.role() = 'authenticated');
    END IF;
END
$$;
